// 채팅방 목록
				+ '<div class="userList" style=" margin-top: -411px;">'
				+ '<ul style="overflow:auto; height: 410px;" />'
				+ '<li class="mschat-li-chatList">' 
					+ '<img src="../../resources/imgs/index/icon_admin.png" alt="나의프로필사진"; style="cursor: pointer;  ">' 
					+'<div class="profile" style="border-bottom: 1px solid #ccc">' 
						+ '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' 
						+ '</a>' 
						+ '<p> ' + 6 + '</p>' 
						+ '<p> 채팅방 번호: ' + 7+ '</p>' 
						//+ '</div>' 
						+ '<div class="chat-status">' 
						+ '<p class="p-chat-status">' + 8 + '</p>' 
						+ '<p class="p-chat-status">' + 9 + '</p>' 
						+ '</div>' 
					+ '</div>' 
				+ '</li></ul></div>'
